
// This file has been generated by the GUI designer. Do not modify.
namespace Docking.Components
{
	public partial class ScriptEditor
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textSource;
		private global::Gtk.TextView textMessage;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Docking.Components.ScriptEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Docking.Components.ScriptEditor";
			// Container child Docking.Components.ScriptEditor.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 119;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textSource = new global::Gtk.TextView ();
			this.textSource.Sensitive = false;
			this.textSource.CanFocus = true;
			this.textSource.Name = "textSource";
			this.GtkScrolledWindow.Add (this.textSource);
			this.vpaned1.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.GtkScrolledWindow]));
			w2.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.textMessage = new global::Gtk.TextView ();
			this.textMessage.CanFocus = true;
			this.textMessage.Name = "textMessage";
			this.textMessage.Editable = false;
			this.vpaned1.Add (this.textMessage);
			this.vbox2.Add (this.vpaned1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vpaned1]));
			w4.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
