
// This file has been generated by the GUI designer. Do not modify.
namespace Docking.Widgets
{
	public partial class Find
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.ComboBoxEntry comboFind;

		private global::Gtk.Label labelStatus;

		private global::Gtk.Button buttonPrev;

		private global::Gtk.Button buttonNext;

		private global::Gtk.Button buttonClear;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Docking.Widgets.Find
			global::Stetic.BinContainer.Attach(this);
			this.Events = ((global::Gdk.EventMask)(3072));
			this.Name = "Docking.Widgets.Find";
			// Container child Docking.Widgets.Find.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.comboFind = global::Gtk.ComboBoxEntry.NewText();
			this.comboFind.Name = "comboFind";
			this.hbox1.Add(this.comboFind);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.comboFind]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelStatus = new global::Gtk.Label();
			this.labelStatus.Name = "labelStatus";
			this.labelStatus.LabelProp = "status";
			this.labelStatus.Justify = ((global::Gtk.Justification)(2));
			this.hbox1.Add(this.labelStatus);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.labelStatus]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonPrev = new global::Gtk.Button();
			this.buttonPrev.CanFocus = true;
			this.buttonPrev.Name = "buttonPrev";
			this.buttonPrev.UseUnderline = true;
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Docking.Framework.Resources.arrow_left-16.png");
			this.buttonPrev.Image = w3;
			this.hbox1.Add(this.buttonPrev);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonPrev]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonNext = new global::Gtk.Button();
			this.buttonNext.CanFocus = true;
			this.buttonNext.Name = "buttonNext";
			this.buttonNext.UseUnderline = true;
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Docking.Framework.Resources.arrow_right-16.png");
			this.buttonNext.Image = w5;
			this.hbox1.Add(this.buttonNext);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonNext]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonClear = new global::Gtk.Button();
			this.buttonClear.CanFocus = true;
			this.buttonClear.Name = "buttonClear";
			this.buttonClear.UseUnderline = true;
			global::Gtk.Image w7 = new global::Gtk.Image();
			w7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Docking.Framework.Resources.cross-16.png");
			this.buttonClear.Image = w7;
			this.hbox1.Add(this.buttonClear);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonClear]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
		}
	}
}
