
// This file has been generated by the GUI designer. Do not modify.
namespace Docking.Components
{
	public partial class ScriptEditor
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.ScrolledWindow scrolledwindow4;
		private global::Gtk.TextView textMessage;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Docking.Components.ScriptEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Docking.Components.ScriptEditor";
			// Container child Docking.Components.ScriptEditor.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 102;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.scrolledwindow4 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow4.CanFocus = true;
			this.scrolledwindow4.Name = "scrolledwindow4";
			this.scrolledwindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vpaned1.Add (this.scrolledwindow4);
			global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.scrolledwindow4]));
			w1.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.textMessage = new global::Gtk.TextView ();
			this.textMessage.CanFocus = true;
			this.textMessage.Name = "textMessage";
			this.textMessage.Editable = false;
			this.vpaned1.Add (this.textMessage);
			this.vbox2.Add (this.vpaned1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vpaned1]));
			w3.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
