
// This file has been generated by the GUI designer. Do not modify.
namespace Docking.Components
{
	public partial class CommandLine
	{
		private global::Gtk.VBox vbox1;
		private global::MonoDevelop.Components.ConsoleView consoleview;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Docking.Components.CommandLine
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Docking.Components.CommandLine";
			// Container child Docking.Components.CommandLine.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.consoleview = new global::MonoDevelop.Components.ConsoleView ();
			this.consoleview.CanFocus = true;
			this.consoleview.Name = "consoleview";
			this.consoleview.AutoIndent = false;
			this.vbox1.Add (this.consoleview);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.consoleview]));
			w1.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
