
// This file has been generated by the GUI designer. Do not modify.
namespace Dock
{
	public partial class TestWidget
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Button buttonPushMe;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Dock.TestWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Dock.TestWidget";
			// Container child Dock.TestWidget.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.buttonPushMe = new global::Gtk.Button ();
			this.buttonPushMe.CanFocus = true;
			this.buttonPushMe.Name = "buttonPushMe";
			this.buttonPushMe.UseUnderline = true;
			this.buttonPushMe.Label = global::Mono.Unix.Catalog.GetString ("Push me...");
			this.fixed1.Add (this.buttonPushMe);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.buttonPushMe]));
			w1.X = 25;
			w1.Y = 21;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonPushMe.Activated += new global::System.EventHandler (this.OnButtonPushMeActivated);
		}
	}
}
