
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action undoAction;
	private global::Gtk.Action QuitAction;
	private global::Gtk.Action addAction;
	private global::Gtk.Action removeAction;
	private global::Gtk.Action ComponentsAction;
	private global::Gtk.Action DummyAction;
	private global::Gtk.Action TestAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar3;
	private global::Gtk.Toolbar theToolBar;
	private global::Docking.DockFrame theDockFrame;
	private global::Gtk.Statusbar theStatusBar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.undoAction = new global::Gtk.Action ("undoAction", null, global::Mono.Unix.Catalog.GetString ("Make all hidden widgets visible again"), "gtk-undo");
		w1.Add (this.undoAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, "<Primary><Mod2>q");
		this.addAction = new global::Gtk.Action ("addAction", global::Mono.Unix.Catalog.GetString ("_Push"), global::Mono.Unix.Catalog.GetString ("Push text to status bar"), "gtk-add");
		this.addAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Push");
		w1.Add (this.addAction, null);
		this.removeAction = new global::Gtk.Action ("removeAction", global::Mono.Unix.Catalog.GetString ("_Pop"), global::Mono.Unix.Catalog.GetString ("Pop text from status bar"), "gtk-remove");
		this.removeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Pop");
		w1.Add (this.removeAction, null);
		this.ComponentsAction = new global::Gtk.Action ("ComponentsAction", global::Mono.Unix.Catalog.GetString ("Components"), null, null);
		this.ComponentsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Components");
		w1.Add (this.ComponentsAction, null);
		this.DummyAction = new global::Gtk.Action ("DummyAction", global::Mono.Unix.Catalog.GetString ("Dummy"), null, null);
		this.DummyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Dummy");
		w1.Add (this.DummyAction, null);
		this.TestAction = new global::Gtk.Action ("TestAction", global::Mono.Unix.Catalog.GetString ("Test"), null, null);
		this.TestAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Test");
		w1.Add (this.TestAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar3'><menu name='FileAction' action='FileAction'><menuitem name='QuitAction' action='QuitAction'/></menu></menubar></ui>");
		this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar3")));
		this.menubar3.Name = "menubar3";
		this.vbox1.Add (this.menubar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='theToolBar'/></ui>");
		this.theToolBar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/theToolBar")));
		this.theToolBar.Name = "theToolBar";
		this.theToolBar.ShowArrow = false;
		this.theToolBar.IconSize = ((global::Gtk.IconSize)(2));
		this.vbox1.Add (this.theToolBar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.theToolBar]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.theDockFrame = new global::Docking.DockFrame ();
		this.theDockFrame.Name = "theDockFrame";
		this.theDockFrame.CompactGuiLevel = 0;
		this.theDockFrame.HandleSize = 4;
		this.theDockFrame.HandlePadding = 0;
		this.theDockFrame.DefaultItemWidth = 100;
		this.theDockFrame.DefaultItemHeight = 100;
		this.theDockFrame.AutoShowDelay = ((uint)(250));
		this.theDockFrame.AutoHideDelay = ((uint)(250));
		this.vbox1.Add (this.theDockFrame);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.theDockFrame]));
		w4.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.theStatusBar = new global::Gtk.Statusbar ();
		this.theStatusBar.Name = "theStatusBar";
		this.theStatusBar.Spacing = 6;
		this.vbox1.Add (this.theStatusBar);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.theStatusBar]));
		w5.Position = 3;
		w5.Expand = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
	}
}
