
// This file has been generated by the GUI designer. Do not modify.
namespace Examples
{
	public partial class PythonExample
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.ComboBox combo;
		private global::Gtk.Button buttonExecute;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textview;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Examples.PythonExample
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Examples.PythonExample";
			// Container child Examples.PythonExample.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.combo = global::Gtk.ComboBox.NewText ();
			this.combo.Name = "combo";
			this.hbox1.Add (this.combo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.combo]));
			w1.Position = 1;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonExecute = new global::Gtk.Button ();
			this.buttonExecute.CanFocus = true;
			this.buttonExecute.Name = "buttonExecute";
			this.buttonExecute.UseUnderline = true;
			this.buttonExecute.Label = global::Mono.Unix.Catalog.GetString ("Execute");
			this.hbox1.Add (this.buttonExecute);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonExecute]));
			w2.Position = 2;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview = new global::Gtk.TextView ();
			this.textview.CanFocus = true;
			this.textview.Name = "textview";
			this.GtkScrolledWindow.Add (this.textview);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w5.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
