
// This file has been generated by the GUI designer. Do not modify.
namespace Examples.VirtualList
{
	public partial class VirtualListView
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label1;
		private global::Gtk.HPaned hpaned2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label2;
		private global::Gtk.HPaned hpaned3;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label3;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label label4;
		private global::Gtk.HBox hbox1;
		private global::Gtk.DrawingArea drawingarea;
		private global::Gtk.VScrollbar vscrollbar1;
		private global::Gtk.HScrollbar hscrollbar1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Examples.VirtualList.VirtualListView
			global::Stetic.BinContainer.Attach (this);
			this.CanFocus = true;
			this.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.Name = "Examples.VirtualList.VirtualListView";
			// Container child Examples.VirtualList.VirtualListView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Events = ((global::Gdk.EventMask)(2162688));
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 61;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Column1");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.hpaned1.Add (this.hbox2);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.hbox2]));
			w2.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.hpaned2 = new global::Gtk.HPaned ();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Events = ((global::Gdk.EventMask)(4194302));
			this.hpaned2.Name = "hpaned2";
			this.hpaned2.Position = 152;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Column2");
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			this.hpaned2.Add (this.hbox3);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.hbox3]));
			w4.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.hpaned3 = new global::Gtk.HPaned ();
			this.hpaned3.CanFocus = true;
			this.hpaned3.Name = "hpaned3";
			this.hpaned3.Position = 61;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Column3");
			this.hbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			this.hpaned3.Add (this.hbox4);
			global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.hpaned3 [this.hbox4]));
			w6.Resize = false;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Column4");
			this.hbox5.Add (this.label4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label4]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			this.hpaned3.Add (this.hbox5);
			this.hpaned2.Add (this.hpaned3);
			this.hpaned1.Add (this.hpaned2);
			this.vbox1.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.drawingarea = new global::Gtk.DrawingArea ();
			this.drawingarea.CanFocus = true;
			this.drawingarea.Events = ((global::Gdk.EventMask)(256));
			this.drawingarea.Name = "drawingarea";
			this.hbox1.Add (this.drawingarea);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.drawingarea]));
			w12.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vscrollbar1 = new global::Gtk.VScrollbar (null);
			this.vscrollbar1.Name = "vscrollbar1";
			this.vscrollbar1.Adjustment.Upper = 100;
			this.vscrollbar1.Adjustment.PageIncrement = 10;
			this.vscrollbar1.Adjustment.PageSize = 10;
			this.vscrollbar1.Adjustment.StepIncrement = 1;
			this.hbox1.Add (this.vscrollbar1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vscrollbar1]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w14.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hscrollbar1 = new global::Gtk.HScrollbar (null);
			this.hscrollbar1.Name = "hscrollbar1";
			this.hscrollbar1.Adjustment.Upper = 100;
			this.hscrollbar1.Adjustment.PageIncrement = 10;
			this.hscrollbar1.Adjustment.PageSize = 10;
			this.hscrollbar1.Adjustment.StepIncrement = 1;
			this.vbox1.Add (this.hscrollbar1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hscrollbar1]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.drawingarea.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawingareaExposeEvent);
			this.vscrollbar1.ValueChanged += new global::System.EventHandler (this.OnVscrollbar1ValueChanged);
			this.hscrollbar1.ValueChanged += new global::System.EventHandler (this.OnHscrollbar1ValueChanged);
		}
	}
}
