
// This file has been generated by the GUI designer. Do not modify.
namespace Examples
{
	public partial class ExampleThreadWorker
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label1;
		private global::Gtk.Button buttonStartThread;
		private global::Gtk.ProgressBar progressbar1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label2;
		private global::Gtk.Button buttonStartTask;
		private global::Gtk.Label labelTaskCount;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label3;
		private global::Gtk.Button buttonEndlessStart;
		private global::Gtk.Button buttonEndlessStop;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Examples.ExampleThreadWorker
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Examples.ExampleThreadWorker";
			// Container child Examples.ExampleThreadWorker.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Docking.Tools.ThreadWorker");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonStartThread = new global::Gtk.Button ();
			this.buttonStartThread.CanFocus = true;
			this.buttonStartThread.Name = "buttonStartThread";
			this.buttonStartThread.UseUnderline = true;
			this.buttonStartThread.Label = global::Mono.Unix.Catalog.GetString ("Start");
			this.hbox1.Add (this.buttonStartThread);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonStartThread]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.progressbar1 = new global::Gtk.ProgressBar ();
			this.progressbar1.Name = "progressbar1";
			this.progressbar1.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.hbox1.Add (this.progressbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.progressbar1]));
			w3.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("System.Factory.Task");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonStartTask = new global::Gtk.Button ();
			this.buttonStartTask.CanFocus = true;
			this.buttonStartTask.Name = "buttonStartTask";
			this.buttonStartTask.UseUnderline = true;
			this.buttonStartTask.Label = global::Mono.Unix.Catalog.GetString ("Start");
			this.hbox2.Add (this.buttonStartTask);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonStartTask]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.labelTaskCount = new global::Gtk.Label ();
			this.labelTaskCount.Name = "labelTaskCount";
			this.labelTaskCount.LabelProp = global::Mono.Unix.Catalog.GetString ("Count: 0");
			this.hbox2.Add (this.labelTaskCount);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.labelTaskCount]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Endless thread");
			this.hbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label3]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonEndlessStart = new global::Gtk.Button ();
			this.buttonEndlessStart.CanFocus = true;
			this.buttonEndlessStart.Name = "buttonEndlessStart";
			this.buttonEndlessStart.UseUnderline = true;
			this.buttonEndlessStart.Label = global::Mono.Unix.Catalog.GetString ("Start");
			this.hbox3.Add (this.buttonEndlessStart);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonEndlessStart]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonEndlessStop = new global::Gtk.Button ();
			this.buttonEndlessStop.Sensitive = false;
			this.buttonEndlessStop.CanFocus = true;
			this.buttonEndlessStop.Name = "buttonEndlessStop";
			this.buttonEndlessStop.UseUnderline = true;
			this.buttonEndlessStop.Label = global::Mono.Unix.Catalog.GetString ("Stop");
			this.hbox3.Add (this.buttonEndlessStop);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonEndlessStop]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonStartThread.Clicked += new global::System.EventHandler (this.OnButtonStartThreadClicked);
			this.buttonStartTask.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
			this.buttonEndlessStart.Clicked += new global::System.EventHandler (this.OnButtonEndlessStartClicked);
			this.buttonEndlessStop.Clicked += new global::System.EventHandler (this.OnButtonEndlessStopClicked);
		}
	}
}
