
// This file has been generated by the GUI designer. Do not modify.
namespace Examples
{
	public partial class PythonExample
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Examples.PythonExample
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Examples.PythonExample";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
