
// This file has been generated by the GUI designer. Do not modify.
namespace Examples.VirtualList
{
	public partial class VirtualListTest
	{
		private global::Examples.VirtualList.VirtualListView virtuallistview1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Examples.VirtualList.VirtualListTest
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Examples.VirtualList.VirtualListTest";
			// Container child Examples.VirtualList.VirtualListTest.Gtk.Container+ContainerChild
			this.virtuallistview1 = new global::Examples.VirtualList.VirtualListView ();
			this.virtuallistview1.Events = ((global::Gdk.EventMask)(256));
			this.virtuallistview1.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.virtuallistview1.Name = "virtuallistview1";
			this.virtuallistview1.RowCount = 0;
			this.Add (this.virtuallistview1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
