
// This file has been generated by the GUI designer. Do not modify.
namespace Examples.HelloWorld
{
	public partial class HelloWorldWidget
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Examples.HelloWorld.HelloWorldWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Examples.HelloWorld.HelloWorldWidget";
			// Container child Examples.HelloWorld.HelloWorldWidget.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Thread Worker");
			this.label2.Justify = ((global::Gtk.Justification)(3));
			this.vbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label2]));
			w1.Position = 1;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
